"""Ajout des champs full_name, mobile, location au modèle Users

Revision ID: b86e0512587c
Revises: 
Create Date: 2025-09-07 00:52:05.181745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86e0512587c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('mobile')
        batch_op.drop_column('full_name')

    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
